-- TABLE DROPING

DROP TABLE T_ANY_TABLE1 CASCADE CONSTRAINTS;

DROP TABLE T_ANY_TABLE2 CASCADE CONSTRAINTS;

-- CREATE TABLES, ADD PRIMARY KEYS AND CONTRAINTS

-- TABLE 1
CREATE TABLE T_ANY_TABLE1
(
    field1  NUMBER(2)     NOT NULL,
    field2  VARCHAR2(60)  NULL,
    field3  DATE          NOT NULL
);

ALTER TABLE T_ANY_TABLE1
    ADD CONSTRAINT PK_ANY_TABLE1 PRIMARY KEY (field1, field2);
    
ALTER TABLE T_ANY_TABLE1
    ADD CONSTRAINT UN_ANY_TABLE1_FIELD3 UNIQUE (field3);    
    
ALTER TABLE T_ANY_TABLE1
    ADD CONSTRAINT CK_SIP_TABLE1_FIELD1  CHECK ( field1 >= 3 ); 

-- TABLE 2
CREATE TABLE T_ANY_TABLE2
(
    field1  NUMBER(2)     NOT NULL,
    field2  VARCHAR2(60)  NULL,
    field3  DATE          NOT NULL
);

ALTER TABLE T_ANY_TABLE2
    ADD CONSTRAINT PK_ANY_TABLE2 PRIMARY KEY (field1, field2);
    
ALTER TABLE T_ANY_TABLE2
    ADD CONSTRAINT UN_ANY_TABLE2_FIELD3 UNIQUE (field3);  
    
ALTER TABLE T_ANY_TABLE2
    ADD CONSTRAINT CK_SIP_TABLE2_FIELD1  CHECK ( field1 >= 3 ); 

-- CREATE FOREIGN KEYS
ALTER TABLE T_ANY_TABLE1
    ADD CONSTRAINT FK_SIP_TABLE2_TABLE1 FOREIGN KEY (field1)
    REFERENCES T_ANY_TABLE2 (field1);